#!/bin/bash
echo "$PWD;docker build -t $IMAGE_NAME --build-arg MY_IMAGE_TAG=$MY_DOCKER_TAG MY_USER=$MY_USER MY_GROUP=$MY_GROUP ."
docker build -t $IMAGE_NAME --build-arg MY_IMAGE_TAG=$MY_DOCKER_TAG MY_USER=$MY_USER MY_GROUP=$MY_GROUP .
